# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: len-foss
org_slug: len-foss
rebel_module_groups: []
repo_description: Odoo addons to ease the development experience
repo_name: Odoo Development Tools
repo_slug: odoo-dev-tools
repo_website: https://github.com/lambdao-dev/odoo-dev-tools
travis_apt_packages: []
travis_apt_sources: []

